services:
  yacht:
    # Default "fresh" login / path: admin@yacht.local / pass
    container_name: yacht
    image: selfhostedpro/yacht
    expose:
      - 8000
    volumes:
      - yacht:/config
      - "${DOCKER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock"
    restart: unless-stopped

volumes:
  yacht: