x-rpc-provider: &rpc-provider
  build:
    context: build/repos/igra-rpc-provider
    dockerfile: ../../Dockerfile.rpc-provider
  image: rpc-provider
  expose:
    - "8535"
  entrypoint: /bin/sh
  command: |
    -c "
    export SERVER_HOST=0.0.0.0;
    export SERVER_PORT=8535;
    export WALLET_DAEMON_URI=http://$${WALLET_HOST}:8082;
    export WALLET_TO_ADDRESS=$$WALLET_TO_ADDRESS;
    export EL_URL=http://execution-layer:8545;
    exec /app/igra-rpc-provider"
  networks:
    - igra-network
    - traefik-network
  logging:
    driver: "json-file"
    options:
      max-size: "100m"
      max-file: "5"
  labels:
    - "traefik.enable=true"
    - >
      traefik.http.routers.rpc.rule=
      PathPrefix(`/9fb27a48631c486b9e5937ac140829d6`) ||
      PathPrefix(`/ad32094f78934ba484bd16c97e20f056`) ||
      PathPrefix(`/e9c4658047e74271b58f203648ac1b3f`) ||
      PathPrefix(`/f73ad68c74924aa9b3e9a12058cf294f`) ||
      PathPrefix(`/17abe38d29cf4037b7045ea621c97f50`) ||
      PathPrefix(`/49df2873ab7946598e0f1ac65b02d14e`) ||
      PathPrefix(`/a2e19f37d58648c9b71c3a5f902d140e`) ||
      PathPrefix(`/c4201b9fea7a4a5f801d2394876e39b4`) ||
      PathPrefix(`/2b8d3945f0174ac8ae9c470d2856e90c`) ||
      PathPrefix(`/85740ace9d164ba59e0c1f39d72b16a3`) ||
      PathPrefix(`/fb8d7c877f0ff3f032143f9dbcc3840a`) ||
      PathPrefix(`/5510d7cfbfc5eb986e0575a3b0496d53`) ||
      PathPrefix(`/fd07318d4a567c187c893a1db9d2f94a`) ||
      PathPrefix(`/1e75a963ab938d39aeed7c51db0be2e6`) ||
      PathPrefix(`/b7c0d14d862d9fa4444ff9e44c731b90`) ||
      PathPrefix(`/25f22c6c1bcadcd80ae1838528dddb8d`) ||
      PathPrefix(`/61e697e1b3f6d2330a84fb875a4d16eb`) ||
      PathPrefix(`/efc258967210a3b231244390dd233186`) ||
      PathPrefix(`/ed528d1a44c0271cba4dba394682a945`) ||
      PathPrefix(`/82d586ce355f11b190e28bb499bbd9e9`) ||
      PathPrefix(`/d1ed97440f59cc1a4030b2c760182e7f`) ||
      PathPrefix(`/4c7c4e51effa50dff827047f20b0bee5`) ||
      PathPrefix(`/c24b3d68bb96f85adf5aebfdd6a409be`) ||
      PathPrefix(`/fdeb9c0eff14aba9f4c7312d693d0f34`) ||
      PathPrefix(`/82f14b862054bcbd45b9018f6b2b14cc`) ||
      PathPrefix(`/fafda38366d687aba4b52a62a08b36d8`)
    - "traefik.http.routers.rpc.entrypoints=rpc"
    - "traefik.http.routers.rpc.middlewares=strip-token"
    - "traefik.http.services.rpc.loadbalancer.server.port=8535"
  healthcheck:
    # Verifies if the container is accepting TCP connections on port 8535 ...
    # ... and can connect to both `execution-layer` and its `kaswallet`
    test: [
      "CMD",
      "bash",
      "-c",
      "echo hello > /dev/tcp/$$HOSTNAME/8535 && \
       echo hello > /dev/tcp/execution-layer/8545 && \
       echo hello > /dev/tcp/$$WALLET_HOST/8082"
    ]
    interval: 10s       # Check every 10 seconds
    timeout: 2s         # Mark as failed if the command takes more than 2 seconds
    retries: 3          # Consider the service unhealthy after 3 failed attempts
    start_period: 5s    # Wait 5 seconds before starting health checks

x-environment: &rpc-common-env
    RUST_LOG: ${RUST_LOG}

x-kaswallet: &kaswallet
  build:
    context: build/repos/kaswallet
    dockerfile: ../../Dockerfile.kaswallet
  image: kaswallet
  extra_hosts:
    - "host.docker.internal:host-gateway"
  environment:
    - RUST_LOG=${RUST_LOG}
    - LOG_LEVEL=${LOG_LEVEL}
  expose:
    - "8082"
  command: >
    --devnet
    --logs-level=${LOG_LEVEL}
    --keys-file /app/keys.json
    --server ws://${KASPAD_HOST}:${KASPAD_BORSH_PORT}
    --listen 0.0.0.0:8082
  networks:
    - igra-network
  logging:
    driver: "json-file"
    options:
      max-size: "100m"
      max-file: "5"
  healthcheck:
    # Verifies if the container is accepting TCP connections on port 8082 and can connect to `kaspad`
    test: [
      "CMD",
      "bash",
      "-c",
      "echo hello > /dev/tcp/$$HOSTNAME/8082 && \
       echo hello > /dev/tcp/${KASPAD_HOST}/${KASPAD_BORSH_PORT}"
    ]
    interval: 10s       # Check every 10 seconds
    timeout: 2s         # Mark as failed if the command takes more than 2 seconds
    retries: 3          # Consider the service unhealthy after 3 failed attempts
    start_period: 5s    # Wait 5 seconds before starting health checks

services:

  rpc-provider-0:
    <<: *rpc-provider
    container_name: rpc-provider-0
    environment:
      <<: *rpc-common-env
      WALLET_HOST: kaswallet-0
      WALLET_TO_ADDRESS: "kaspadev:qpm06zv507sh59hjevsmkkgj9kv0q7a02wtnxt6l9qcvjk7dqtysy9kg4u3um"
      KASWALLET_PASSWORD: ''
    depends_on:
      kaswallet-0:
        condition: service_healthy

  kaswallet-0:
    <<: *kaswallet
    container_name: kaswallet-0
    volumes:
      - ./keys/keys.kaswallet-0.json:/app/keys.json

  rpc-provider-1:
    <<: *rpc-provider
    container_name: rpc-provider-1
    environment:
      <<: *rpc-common-env
      WALLET_HOST: kaswallet-1
      WALLET_TO_ADDRESS: "kaspadev:qpm06zv507sh59hjevsmkkgj9kv0q7a02wtnxt6l9qcvjk7dqtysy9kg4u3um"
      KASWALLET_PASSWORD: ''
    depends_on:
      kaswallet-1:
        condition: service_healthy

  kaswallet-1:
    <<: *kaswallet
    container_name: kaswallet-1
    volumes:
      - ./keys/keys.kaswallet-1.json:/app/keys.json

  rpc-provider-2:
    <<: *rpc-provider
    container_name: rpc-provider-2
    environment:
      <<: *rpc-common-env
      WALLET_HOST: kaswallet-2
      WALLET_TO_ADDRESS: "kaspadev:qpm06zv507sh59hjevsmkkgj9kv0q7a02wtnxt6l9qcvjk7dqtysy9kg4u3um"
      KASWALLET_PASSWORD: ''
    depends_on:
      kaswallet-2:
        condition: service_healthy

  kaswallet-2:
    <<: *kaswallet
    container_name: kaswallet-2
    volumes:
      - ./keys/keys.kaswallet-2.json:/app/keys.json

  rpc-provider-3:
    <<: *rpc-provider
    container_name: rpc-provider-3
    environment:
      <<: *rpc-common-env
      WALLET_HOST: kaswallet-3
      WALLET_TO_ADDRESS: "kaspadev:qpm06zv507sh59hjevsmkkgj9kv0q7a02wtnxt6l9qcvjk7dqtysy9kg4u3um"
      KASWALLET_PASSWORD: ''
    depends_on:
      kaswallet-3:
        condition: service_healthy

  kaswallet-3:
    <<: *kaswallet
    container_name: kaswallet-3
    volumes:
      - ./keys/keys.kaswallet-3.json:/app/keys.json

  rpc-provider-4:
    <<: *rpc-provider
    container_name: rpc-provider-4
    environment:
      <<: *rpc-common-env
      WALLET_HOST: kaswallet-4
      WALLET_TO_ADDRESS: "kaspadev:qpm06zv507sh59hjevsmkkgj9kv0q7a02wtnxt6l9qcvjk7dqtysy9kg4u3um"
      KASWALLET_PASSWORD: ''
    depends_on:
      kaswallet-4:
        condition: service_healthy

  kaswallet-4:
    <<: *kaswallet
    container_name: kaswallet-4
    volumes:
      - ./keys/keys.kaswallet-4.json:/app/keys.json

  rpc-provider-5:
    <<: *rpc-provider
    container_name: rpc-provider-5
    environment:
      <<: *rpc-common-env
      WALLET_HOST: kaswallet-5
      WALLET_TO_ADDRESS: "kaspadev:qpm06zv507sh59hjevsmkkgj9kv0q7a02wtnxt6l9qcvjk7dqtysy9kg4u3um"
      KASWALLET_PASSWORD: ''
    depends_on:
      kaswallet-5:
        condition: service_healthy

  kaswallet-5:
    <<: *kaswallet
    container_name: kaswallet-5
    volumes:
      - ./keys/keys.kaswallet-5.json:/app/keys.json

networks:
  igra-network:
    name: igra-network
  traefik-network:
    name: traefik-network
