services:
  kaspa_explorer:
    image: supertypo/kaspa-explorer:latest
    container_name: kaspa_explorer
    restart: unless-stopped
    expose:
      - "8080"
    environment:
      REACT_APP_NETWORK: "Igra Devnet"
      API_URI: "${KASPA_EXPLORER_API_URI}"
      API_WS_URI: "${KASPA_EXPLORER_WS_URI}"
    networks:
      - kaspa-explorer-network
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.explorer.rule=PathPrefix(`/`)"
      - "traefik.http.routers.explorer.entrypoints=explorer_http"
      - "traefik.http.services.explorer.loadbalancer.server.port=8080"

  simply_kaspa_socket_server:
    image: supertypo/simply-kaspa-socket-server:unstable
    container_name: simply_kaspa_socket_server
    restart: unless-stopped
    expose:
      - "8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: "-n devnet -x 20 -s ws://${KASPAD_HOST}:${KASPAD_BORSH_PORT}"
    networks:
      - kaspa-explorer-network
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.socket.rule=PathPrefix(`/`)"
      - "traefik.http.routers.socket.entrypoints=explorer_ws"
      - "traefik.http.services.socket.loadbalancer.server.port=8000"
      - "traefik.http.routers.socket.middlewares=ws-headers"
      - "traefik.http.middlewares.ws-headers.headers.customrequestheaders.Connection=upgrade"
      - "traefik.http.middlewares.ws-headers.headers.customrequestheaders.Upgrade=websocket"

  kaspa_rest_server:
    image: kaspanet/kaspa-rest-server:latest
    container_name: kaspa_rest_server
    restart: unless-stopped
    expose:
      - "8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      KASPAD_HOST_1: "${KASPAD_HOST}:${KASPAD_BORSH_PORT}"
      SQL_URI: "postgresql+asyncpg://postgres:postgres@kaspa_db:5432/postgres"
    networks:
      - kaspa-explorer-network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

  simply_kaspa_indexer:
    image: supertypo/simply-kaspa-indexer:latest
    container_name: simply_kaspa_indexer
    restart: unless-stopped
    environment:
      SQL_URI: "postgresql://postgres:postgres@kaspa_db:5432/postgres"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: "-n devnet -u -s ws://${KASPAD_HOST}:${KASPAD_BORSH_PORT} -d $${SQL_URI}"
    networks:
      - kaspa-explorer-network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

  kaspa_db:
    image: postgres:16-alpine
    container_name: kaspa_db
    restart: unless-stopped
    shm_size: 4G
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    expose:
      - "5432"
    volumes:
      - "/var/kaspa_db/:/var/lib/postgresql/data/"
    networks:
      - kaspa-explorer-network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

networks:
  kaspa-explorer-network:
    name: kaspa-explorer-network
  traefik-network:
    name: traefik-network
